### ISSUE TITLE
该用户不存在

### ISSUE THREAD

**Issue by weaming** [fjc0k/docker-YApi#112]
```
version: '3'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 3000:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=admin
      - YAPI_ADMIN_PASSWORD=123
      - YAPI_DB_AUTH_SOURCE=admin
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[]
    depends_on:
      - yapi-mongo
    links:
      - yapi-mongo
    restart: unless-stopped
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - ~/data/yapi-mongo:/data/db
    expose:
      - 27017
    restart: unless-stopped
```
