### ISSUE TITLE
创建yapi失败

### ISSUE THREAD

**Issue by MalavitaC** [fjc0k/docker-YApi#8]
> YApi 正在启动...
> 启动引导服务...
> 写入配置...
> ```
> {
>   "adminAccount": "923145852@qq.com",
>   "db": {
>     "servername": "yapi-mongo",
>     "port": 27017,
>     "DATABASE": "yapi",
>     "user": "mongo",
>     "pass": "admin"
>   },
>   "mail": {
>     "enable": false,
>     "auth": {}
>   },
>   "ldapLogin": {
>     "enable": false
>   },
>   "closeRegister": true,
>   "plugins": [
>     {
>       "name": "add-user"
>     },
>     {
>       "name": "webhook"
>     },
>     {
>       "name": "add-user"
>     },
>     {
>       "name": "webhook"
>     }
>   ],
>   "adminPassword": "admin",
>   "port": 3000
> }
> ```
> 等待 MongoDB 服务可用...
> 安装 YApi 插件...
> + cd /yapi/vendors
> + npm install yapi-plugin-add-user yapi-plugin-webhook yapi-plugin-add-user yapi-plugin-webhook --no-audit
> 
> npm
>  WARN mongoose-auto-increment@5.0.1 requires a peer of mongoose@^4.1.12 but none is installed. You must install peer dependencies yourself.
> npm WARN sass-loader@7.0.3 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
> npm 
> WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none is installed. You must install peer dependencies yourself.
> npm WARN
>  react-slick@0.15.4 requires a peer of react@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
> npm WARN react-slick@0.15.4 requires a peer of react-dom@^0.14.0 || ^15.0.1 but none is installed. You must install peer dependencies yourself.
> 
> 
> 
> + yapi-plugin-webhook@1.1.6
> + yapi-plugin-webhook@1.1.6
> + yapi-plugin-add-user@0.0.1
> + yapi-plugin-add-user@0.0.1
> updated 2 packages in 30.177s
> 
> 
> 1 package is looking for funding
>   run `npm fund` for details
> 
> 
> + npm run build-client
> 
> 
> > yapi-vendor@1.8.5 build-client /yapi/vendors
> > NODE_ENV=production ykit pack -m
> 
> 
> 
> ---------------------  YKIT EMITTED ASSETS  ---------------------
> 
> 
> [ykit] - lib@766f2c2210e784a94dad.js - 165.17 KB
> 
> [ykit] - manifest@f2f4bd774d6c221b3d5f.js - 713 Bytes
> 
> [ykit] - lib2@df83401c743294e39034.js - 373.47 KB
> 
> [ykit] - index@d7b40e6e23301200de15.css - 521.36 KB
> 
> [ykit] - lib3@80beea5f18a86f24cb05.js - 735.40 KB
> 
> [ykit] - index@d7b40e6e23301200de15.js - 4957.19 KB
> 
> [info] Bundling Finishes in 92s.
> 
> 
> 尝试安装 YApi...
### 一直停在尝试安装

**Comment by fjc0k** [comment]
docker-compose 你改了吧，把它发出来

**Comment by MalavitaC** [comment]
```
ersion: '3.7'

services:
  yapi-web:
    image: jayfong/yapi:latest
    container_name: yapi-web
    ports:
      - 8082:3000
    environment:
      - YAPI_ADMIN_ACCOUNT=923145852@qq.com
      - YAPI_ADMIN_PASSWORD=admin
      - YAPI_CLOSE_REGISTER=true
      - YAPI_DB_SERVERNAME=yapi-mongo
      - YAPI_DB_PORT=27017
      - YAPI_DB_DATABASE=yapi
      - YAPI_DB_USER=mongo
      - YAPI_DB_PASS=admin
      - YAPI_MAIL_ENABLE=false
      - YAPI_LDAP_LOGIN_ENABLE=false
      - YAPI_PLUGINS=[{"name":"add-user"},{"name":"webhook"}]
    volumes:
      - ./data/yapi-vendors:/yapi/vendors
    depends_on:
      - yapi-mongo
    restart: unless-stopped
  yapi-mongo:
    image: mongo:latest
    container_name: yapi-mongo
    volumes:
      - yapi-data:/data/db
    expose:
      - 27017
    restart: unless-stopped

volumes:
    yapi-data:
```
